name: Build Android Template App

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-template-android.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/build-template-android.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'

jobs:
  build:
    name: Build Android Template App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-native-template-pytorch-live/template/android
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules for react-native-pytorch-core
        run: yarn install --frozen-lockfile
        working-directory: ./react-native-pytorch-core
      - name: Install node_modules for template
        run: yarn install --frozen-lockfile --cwd ..
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Build
        run: ./gradlew assembleDebug
